const ADDITION = '+';
const SUBSTRACTION = '-';
const MULTIPLICATION = '*';
const DIVISION = '/';
const RESULT = 'RESULT';
const CLEAR = 'CLEAR';
const NUMBER = 'NUMBER';

module.exports = {ADDITION,SUBSTRACTION,MULTIPLICATION,DIVISION,RESULT,CLEAR,NUMBER}